// Deterministic statement-line classifier.  It deliberately has no LLM call:
// its job is to make a proposed mapping explainable and to abstain where the
// available source evidence cannot distinguish economic treatments.
import fs from "node:fs";

const TAXONOMY = JSON.parse(fs.readFileSync(
  new URL("../../assets/statement-semantic-taxonomy.v1.json", import.meta.url), "utf8",
));

function normalise(value) {
  return String(value ?? "").toLowerCase().replaceAll(/[^a-z0-9]+/g, " ").trim();
}

function wordList(value) {
  return normalise(value).split(" ").filter(Boolean);
}

function words(value) {
  return new Set(wordList(value));
}

function phraseMatch(label, phrase) {
  // An alias is a complete disclosure label, not a substring. Otherwise the
  // word "revenue" makes "cost of revenue" look equally like top-line sales.
  return normalise(label) === normalise(phrase);
}

// ---------------------------------------------------------------------------
// Printed-caption grammar.
//
// A filed caption is rarely the bare alias.  Issuers print the alias wrapped in
// qualifiers: an entity-scope modifier in front ("Group revenue"), a restrictive
// prepositional tail ("Revenue FROM CONTRACTS WITH CUSTOMERS"), or a connective
// the role's own alias vocabulary already contains ("Net cash GENERATED from
// operating activities", where the role itself declares "cash generated by
// operating activities").  None of those change the disclosed concept.
//
// Before this grammar existed the whole caption fell through to the token
// channel, where a family head and a family member score identically because
// they SHARE tokens: `cost_of_sales` declares "revenue" only because it must
// match "cost of revenue", so "Revenue from contracts with customers" earned
// `cost_of_sales` exactly as much label evidence as `revenue` — a structurally
// unbreakable 0.00 margin.  Reading the caption as alias-plus-qualifier resolves
// it on the issuer's own declared vocabulary instead of on shared tokens.
//
// The guards below are what keep this from becoming a widened gate: a qualifier
// that carries ANOTHER role's declared evidence refuses the match outright, so a
// caption naming two roles ("Revenue less cost of sales", "Net cash from
// operating and investing activities") resolves to neither.
// ---------------------------------------------------------------------------

// Entity/aggregation scope. Every word here is asserted (by the caption-defect
// suite) to be a token of no role at all, so it can never smuggle in evidence.
const LEADING_SCOPE_MODIFIERS = Object.freeze([
  "group", "consolidated", "combined", "aggregate", "total", "segment",
]);

// Words that introduce a restrictive qualifier rather than a second concept. A
// conjunction ("and", "less", "plus") is deliberately absent: it announces that
// the caption names more than one thing.
const TRAILING_QUALIFIER_INTRODUCERS = Object.freeze([
  "from", "with", "under", "by", "to", "in", "on", "at", "for", "of",
  "attributable", "arising", "relating", "related", "derived",
]);

// A connective announces that the caption states an ARITHMETIC over two
// concepts ("Revenue less cost of sales") rather than naming one.  A connective
// appearing as a qualifier refuses the match in ANY position, and is never
// reclaimable: it is the one qualifier class that changes what the caption says.
const CAPTION_CONNECTIVES = Object.freeze([
  "and", "or", "less", "plus", "minus", "add", "deduct", "versus", "vs",
  "including", "excluding",
]);

const LEADING_SCOPE_MODIFIER_SET = new Set(LEADING_SCOPE_MODIFIERS);
const TRAILING_QUALIFIER_INTRODUCER_SET = new Set(TRAILING_QUALIFIER_INTRODUCERS);
const CAPTION_CONNECTIVE_SET = new Set(CAPTION_CONNECTIVES);

// A word carries classification evidence exactly when some role declares it as
// a discriminating token. Anything else is inert text.
const EVIDENCE_BEARING_WORDS = new Set(
  TAXONOMY.roles
    .flatMap((role) => role.tokens ?? [])
    .map((token) => normalise(token))
    .filter((token) => token && !token.includes(" ")),
);

// Each role's own declared vocabulary, drawn from its own alias list.
const ROLE_ALIAS_WORDS = new Map(TAXONOMY.roles.map((role) => [
  role.id,
  new Set((role.aliases ?? []).flatMap((alias) => wordList(alias))),
]));

/** Split a caption around an alias occurring as an ordered subsequence. */
function aliasQualifierSplit(labelWords, aliasWords) {
  const positions = [];
  let cursor = 0;
  for (const word of aliasWords) {
    const at = labelWords.indexOf(word, cursor);
    if (at === -1) return null;
    positions.push(at);
    cursor = at + 1;
  }
  const first = positions[0];
  const last = positions[positions.length - 1];
  const matched = new Set(positions);
  return {
    leading: labelWords.slice(0, first),
    internal: labelWords.slice(first, last + 1).filter((_, index) => !matched.has(first + index)),
    trailing: labelWords.slice(last + 1),
  };
}

function qualifiedAliasFor(role, labelWords) {
  const ownWords = ROLE_ALIAS_WORDS.get(role.id) ?? new Set();
  const declaredByThisRole = (word) => ownWords.has(word);
  const inert = (word) => !EVIDENCE_BEARING_WORDS.has(word);
  let best = null;
  for (const alias of role.aliases ?? []) {
    const aliasWords = wordList(alias);
    if (aliasWords.length === 0) continue;
    const split = aliasQualifierSplit(labelWords, aliasWords);
    if (!split) continue;
    const qualifiers = [...split.leading, ...split.internal, ...split.trailing];
    // A connective anywhere means the caption states an arithmetic over two
    // concepts, not the name of one. Never reclaimable, in any position.
    if (qualifiers.some((word) => CAPTION_CONNECTIVE_SET.has(word))) continue;
    // In front: a declared scope modifier, or a word this role's own aliases use.
    if (!split.leading.every((word) => LEADING_SCOPE_MODIFIER_SET.has(word) || declaredByThisRole(word))) continue;
    // Inside: inert text, or a word this role's own aliases use.
    if (!split.internal.every((word) => inert(word) || declaredByThisRole(word))) continue;
    // Behind: a restrictive qualifier phrase, and nothing that carries another
    // role's evidence. No reclaim here — a tail is where a second concept hides.
    if (split.trailing.length > 0 &&
      !(TRAILING_QUALIFIER_INTRODUCER_SET.has(split.trailing[0]) && split.trailing.every(inert))) continue;
    if (!best || aliasWords.length > best.specificity) {
      best = { role: role.id, alias: normalise(alias), specificity: aliasWords.length, qualifiers };
    }
  }
  return best;
}

/**
 * Resolve a printed caption to at most ONE role by reading it as a declared
 * alias plus qualifiers.  Exported so the guards can be mutation-tested.
 * Returns null when the caption is a literal alias (the exact-match channel is
 * strictly better evidence), when no role's vocabulary fits, or when two roles
 * fit equally well — an equal fit is a real ambiguity and is awarded to neither.
 */
export function resolveQualifiedAliasCaption(label) {
  const labelWords = wordList(label);
  if (labelWords.length === 0) return null;
  const exact = TAXONOMY.roles.some(
    (role) => (role.aliases ?? []).some((alias) => phraseMatch(label, alias)),
  );
  if (exact) return null;
  const matches = [];
  for (const role of TAXONOMY.roles) {
    const match = qualifiedAliasFor(role, labelWords);
    if (match) matches.push(match);
  }
  if (matches.length === 0) return null;
  matches.sort((a, b) => b.specificity - a.specificity || a.role.localeCompare(b.role));
  if (matches.length > 1 && matches[1].specificity === matches[0].specificity) return null;
  return matches[0];
}

/** The caption grammar, published so it can be audited and mutation-tested. */
export const CAPTION_QUALIFIER_RULES = Object.freeze({
  leading_scope_modifiers: LEADING_SCOPE_MODIFIERS,
  trailing_qualifier_introducers: TRAILING_QUALIFIER_INTRODUCERS,
  caption_connectives: CAPTION_CONNECTIVES,
});

function contextText(line) {
  return [line.parent_label, ...(line.neighbouring_labels ?? []), line.table_context]
    .filter(Boolean).join(" ");
}

function candidateFor(role, line, qualifiedAlias = null) {
  const label = normalise(line.label);
  const labelWords = words(label);
  const context = contextText(line);
  const numericType = line.numeric_type ??
    // WORD boundaries, not substrings. Unanchored, "rate" matched inside
    // "gene-RATE-d", so "Cash generated by operating activities" — a DECLARED
    // alias — was scored as a percentage line and penalised 0.60 against its
    // own currency role.
    (line.number_format === "percentage" ||
      /\b(?:margins?|rates?|percent(?:age)?s?)\b/i.test(line.label ?? "")
      ? "percentage"
      : (line.values ?? []).some(
          (value) => value !== null && value !== "" && Number.isFinite(Number(value)),
        )
        ? "currency"
        : null);
  const evidence = [];
  let score = 0;
  const exact = role.aliases.some((alias) => phraseMatch(label, alias));
  // A caption that is this role's declared alias wrapped in qualifiers is that
  // alias: same concept, same weight. The qualifier guards live in
  // resolveQualifiedAliasCaption, which awards at most one role per caption.
  const qualified = !exact && qualifiedAlias?.role === role.id ? qualifiedAlias : null;
  if (exact || qualified) {
    score += 0.65;
    evidence.push({ channel: "label", detail: "declared alias", score: 0.65 });
  } else {
    // NOTE (deliberate, load-bearing): the token channel is NOT gated on the
    // role's mandatory vocabulary, even though a role scoring off a token it
    // only declares to reach a different caption is sloppy evidence.  Gating it
    // was tried and reverted: this classifier abstains by comparing the leader
    // against the RUNNER-UP, so withholding a competitor's evidence widens the
    // separation margin and makes acceptance easier.  Proven case — "Issuer-
    // specific Core operating result" under parent "Core EBITDA": gating dropped
    // adjusted_ebitda 0.76 -> 0.62, and adjusted_ebit went from correctly
    // abstaining at margin 0.14 to ACCEPTING at 0.90.  EBIT is not EBITDA.
    // Sloppy competitor evidence is doing real work as an ambiguity signal;
    // removing it weakens the margin validator.  Fix the winner's evidence
    // (see the caption grammar above), never the loser's.
    const matches = role.tokens.filter((token) => labelWords.has(normalise(token)));
    if (matches.length > 0) {
      const tokenScore = Math.min(0.42, matches.length * 0.14);
      score += tokenScore;
      evidence.push({ channel: "label", detail: `tokens: ${matches.join(", ")}`, score: tokenScore });
    }
  }
  if (role.negative_tokens?.some((token) => labelWords.has(normalise(token)))) {
    score -= 0.5;
    evidence.push({ channel: "negative", detail: "excluded label token", score: -0.5 });
  }
  if (role.sections.includes(line.section)) {
    score += 0.2;
    evidence.push({ channel: "statement", detail: `statement: ${line.section}`, score: 0.2 });
  } else {
    score -= 0.35;
    evidence.push({ channel: "context", detail: `wrong statement: ${line.section}`, score: -0.35 });
  }
  const contextWords = words(context);
  const contextMatches = role.tokens.filter((token) => contextWords.has(normalise(token)));
  if (contextMatches.length > 0) {
    score += 0.12;
    evidence.push({ channel: "hierarchy", detail: `context tokens: ${contextMatches.join(", ")}`, score: 0.12 });
  }
  if (Array.isArray(role.numeric_types) && numericType) {
    if (role.numeric_types.includes(numericType)) {
      score += 0.1;
      evidence.push({ channel: "numeric_type", detail: `numeric type: ${numericType}`, score: 0.1 });
    } else {
      score -= 0.6;
      evidence.push({ channel: "negative", detail: `incompatible numeric type: ${numericType}`, score: -0.6 });
    }
  } else if (numericType === "currency") {
    score += 0.05;
    evidence.push({ channel: "numeric_type", detail: "statement currency value", score: 0.05 });
  } else if (numericType === "percentage") {
    score -= 0.45;
    evidence.push({ channel: "negative", detail: "percentage cannot own a currency role", score: -0.45 });
  }
  if (
    role.adjustment_basis === true &&
    ["adjusted", "core", "underlying"].some((token) => labelWords.has(token))
  ) {
    score += 0.12;
    evidence.push({ channel: "definition_basis", detail: "company-adjusted basis", score: 0.12 });
  }
  if (line.is_subtotal === true && ["operating_profit", "ebit", "adjusted_ebit", "reported_ebitda", "adjusted_ebitda"].includes(role.id)) {
    score += 0.08;
    evidence.push({ channel: "structure", detail: "source subtotal", score: 0.08 });
  }
  const arithmeticEvidence = Array.isArray(line.arithmetic_evidence)
    ? line.arithmetic_evidence.filter((item) => item?.role === role.id || item?.role === undefined)
    : [];
  if (line.arithmetic_reconciled === true || arithmeticEvidence.length > 0) {
    const arithmeticScore = line.arithmetic_reconciled === true ? 0.12 : 0.08;
    score += arithmeticScore;
    evidence.push({
      channel: "arithmetic",
      detail: arithmeticEvidence.map((item) => item.detail).filter(Boolean).join("; ") ||
        "source arithmetic reconciles the candidate role",
      score: arithmeticScore,
    });
  }
  return { role: role.id, score: Math.max(0, Math.min(1, score)), evidence, high_impact: role.high_impact };
}

function auditFields({ status, classifiedRole, best, next, candidates, qualifiedAlias = null }) {
  const evidence = best?.evidence ?? [];
  const byChannels = (...channels) => evidence.filter((item) => channels.includes(item.channel));
  return {
    candidate_roles: candidates.map(({ role, score }) => ({
      role,
      score: Number(score.toFixed(2)),
    })),
    alias_evidence: byChannels("label").filter((item) => item.detail === "declared alias"),
    // Which declared alias the printed caption was read as, and which qualifier
    // words were treated as scope rather than concept.
    caption_alias_resolution: qualifiedAlias
      ? {
        role: qualifiedAlias.role,
        alias: qualifiedAlias.alias,
        qualifiers: qualifiedAlias.qualifiers,
      }
      : null,
    context_evidence: byChannels("statement", "context", "hierarchy", "definition_basis"),
    structural_evidence: byChannels("structure"),
    arithmetic_evidence: byChannels("arithmetic"),
    negative_evidence: evidence.filter((item) => item.score < 0 || item.channel === "negative"),
    margin: best ? Number((best.score - (next?.score ?? 0)).toFixed(2)) : 0,
    final_disposition: {
      status,
      role: classifiedRole,
      reason: status === "accepted"
        ? "accepted_with_independent_evidence"
        : status === "ambiguous"
          ? "insufficient_or_unseparated_evidence"
          : "no_supported_candidate",
    },
  };
}

/**
 * Return an accepted classification only when evidence clears an explicit
 * threshold. `ambiguous` and `unmapped` are valid, intentional outcomes.
 */
export function classifyStatementLine(line) {
  if (!line?.label || !line?.section) {
    throw new Error("Statement classification requires a label and statement section.");
  }
  // Resolved once per caption, not once per role: the resolution is a property
  // of the printed label and awards at most one role.
  const qualifiedAlias = resolveQualifiedAliasCaption(line.label);
  const candidates = TAXONOMY.roles
    .map((role) => candidateFor(role, line, qualifiedAlias))
    .filter((candidate) => candidate.score > 0)
    .sort((a, b) => b.score - a.score || a.role.localeCompare(b.role));
  const best = candidates[0] ?? null;
  const next = candidates[1] ?? null;
  if (!best || best.score < 0.6) {
    const status = "unmapped";
    const compactCandidates = candidates.map(({ role, score }) => ({ role, score: Number(score.toFixed(2)) }));
    return {
      taxonomy_version: TAXONOMY.contract_version,
      status,
      classified_role: null,
      confidence: 0,
      evidence: [],
      candidates: compactCandidates,
      ...auditFields({ status, classifiedRole: null, best, next, candidates, qualifiedAlias }),
    };
  }
  const channels = new Set(best.evidence.filter((item) => item.score > 0).map((item) => item.channel));
  const substantiveChannels = new Set(
    [...channels].filter(
      (channel) => !["label", "statement", "definition_basis"].includes(channel),
    ),
  );
  const separated = !next || best.score - next.score >= 0.15;
  // An alias plus the expected statement is discovery, not authority. Every
  // accepted role needs at least one independent substantive channel (numeric
  // type, hierarchy or source structure), regardless of impact tier.
  const sufficientlySupported = substantiveChannels.size >= 1;
  const accepted = best.score >= 0.85 && separated && sufficientlySupported;
  const status = accepted ? "accepted" : "ambiguous";
  const classifiedRole = accepted ? best.role : null;
  return {
    taxonomy_version: TAXONOMY.contract_version,
    status,
    classified_role: classifiedRole,
    confidence: Number(best.score.toFixed(2)),
    evidence: best.evidence,
    candidates: candidates.map(({ role, score }) => ({ role, score: Number(score.toFixed(2)) })),
    ...auditFields({ status, classifiedRole, best, next, candidates, qualifiedAlias }),
  };
}

export function isHighImpactRole(role) {
  return TAXONOMY.roles.some((entry) => entry.id === role && entry.high_impact);
}

function roleLabel(role) {
  return String(role ?? "other treatment").replaceAll("_", " ");
}

/**
 * Produce only the material ambiguities that can change cash, debt, interest,
 * tax, leases, FX or an operating subtotal.  These are presented together at
 * the one permitted clarification stop; they are never silently defaulted.
 */
export function planStatementClassificationQuestions(modelCase) {
  const coverage = modelCase?.source_coverage ?? {};
  const questions = [];
  for (const section of ["income_statement", "cash_flow"]) {
    for (const disclosure of coverage[section] ?? []) {
      if (["accepted", "manual_reviewed"].includes(disclosure.classification_status)) continue;
      const classification = classifyStatementLine({ ...disclosure, section });
      const materialOrHighImpact = disclosure.material === true ||
        classification.candidates.some((candidate) => isHighImpactRole(candidate.role));
      if (!materialOrHighImpact || classification.status === "accepted") continue;
      const candidates = classification.candidates.slice(0, 3).map((candidate) => ({
        role: candidate.role,
        label: roleLabel(candidate.role),
        confidence: candidate.score,
      }));
      questions.push({
        id: `statement-classification.${disclosure.source_line_id ?? "missing"}`,
        source_line_id: disclosure.source_line_id ?? null,
        source_label: disclosure.label ?? disclosure.source_line_id ?? "unnamed disclosure",
        section,
        prompt: `How should “${disclosure.label ?? disclosure.source_line_id ?? "this disclosure"}” in the ${roleLabel(section)} be treated?`,
        candidates,
        reason: classification.status === "unmapped"
          ? "The available evidence does not support a material economic classification."
          : "The available evidence supports more than one material economic treatment.",
        resolution_required: true,
      });
    }
  }
  return questions;
}
