#!/usr/bin/env node
/**
 * P1.1 — The canonical contract generator.
 *
 * One versioned interface definition (assets/contracts/*.contract.json)
 * generates the JSON Schema, the JavaScript binding and the Python binding.
 * Generation is DETERMINISTIC: same definition bytes -> same generated bytes.
 * `--check` fails when the committed generated artifacts differ from what the
 * definitions produce (the generated-diff cleanliness gate for CI).
 *
 * The definition format supports objects, maps, arrays, enums, consts,
 * discriminated unions, references, patterns and required-vs-optional —
 * chosen over an external IDL because the release closure is sealed and
 * vendored dependencies are policy-bound; the format is owned here.
 */
import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");
const CONTRACTS_DIR = path.join(ROOT, "assets", "contracts");
const GENERATED_SCHEMA_DIR = path.join(ROOT, "assets", "generated");
const GENERATED_JS_DIR = path.join(ROOT, "scripts", "lib", "generated");
const GENERATED_PY_DIR = path.join(ROOT, "scripts", "generated");
const CHECK = process.argv.includes("--check");

function fieldToSchema(field, enums, types) {
  switch (field.type) {
    case "string": {
      const schema = { type: "string" };
      if (field.pattern) schema.pattern = field.pattern;
      return schema;
    }
    case "boolean": return { type: "boolean" };
    case "number": return { type: "number" };
    case "null": return { type: "null" };
    case "const": return { const: field.const };
    case "enum": return { enum: enums[field.enum] };
    case "array": return { type: "array", items: fieldToSchema(field.items, enums, types) };
    case "map": return {
      type: "object",
      additionalProperties: fieldToSchema(field.values, enums, types),
    };
    case "ref": return { $ref: `#/definitions/${field.ref}` };
    default: throw new Error(`Unknown field type ${field.type}`);
  }
}

function objectToSchema(definition, enums, types) {
  if (definition.kind === "object") {
    const properties = {};
    const required = [];
    for (const [name, field] of Object.entries(definition.fields)) {
      properties[name] = fieldToSchema(field, enums, types);
      if (field.required) required.push(name);
    }
    return { type: "object", additionalProperties: false, properties, required };
  }
  if (definition.kind === "discriminated_union") {
    return {
      oneOf: Object.values(definition.variants).map((variant) =>
        objectToSchema({ kind: "object", fields: variant.fields }, enums, types)),
    };
  }
  throw new Error(`Unknown definition kind ${definition.kind}`);
}

function generateSchema(contract) {
  return {
    $schema: "http://json-schema.org/draft-07/schema#",
    title: contract.contract,
    description: `GENERATED by compile_canonical_contracts.mjs from assets/contracts/${contract.contract.replace(/_/g, "-")}.contract.json — do not edit.`,
    contract_version: contract.version,
    definitions: Object.fromEntries(
      Object.entries(contract.types).map(([name, definition]) => [
        name, objectToSchema(definition, contract.enums, contract.types),
      ]),
    ),
    ...objectToSchema(contract.root, contract.enums, contract.types),
  };
}

function generateJs(contract) {
  return `// GENERATED by compile_canonical_contracts.mjs — do not edit.
// Contract: ${contract.contract} v${contract.version}
// Validation walks the DEFINITION semantics directly (objects, maps, arrays,
// enums, consts, discriminated unions, refs, patterns) — deliberately NOT the
// repository JSON-Schema validator, which does not enforce oneOf/$ref.
export const CONTRACT_NAME = ${JSON.stringify(contract.contract)};
export const CONTRACT_VERSION = ${JSON.stringify(contract.version)};
export const SUPPORTED_VERSIONS = ${JSON.stringify(contract.supported_versions)};
const ENUMS = ${JSON.stringify(contract.enums)};
const TYPES = ${JSON.stringify(contract.types)};
const ROOT = ${JSON.stringify(contract.root)};
${Object.entries(contract.enums).map(([name, values]) =>
    `export const ${name} = Object.freeze(${JSON.stringify(values)});`).join("\n")}

function checkField(field, value, at, errors) {
  switch (field.type) {
    case "string":
      if (typeof value !== "string") errors.push(\`\${at}: expected string\`);
      else if (field.pattern && !new RegExp(field.pattern).test(value)) errors.push(\`\${at}: pattern mismatch\`);
      break;
    case "boolean":
      if (typeof value !== "boolean") errors.push(\`\${at}: expected boolean\`);
      break;
    case "number":
      if (typeof value !== "number" || Number.isNaN(value)) errors.push(\`\${at}: expected number\`);
      break;
    case "null":
      if (value !== null) errors.push(\`\${at}: expected null\`);
      break;
    case "const":
      if (value !== field.const) errors.push(\`\${at}: expected const \${JSON.stringify(field.const)}\`);
      break;
    case "enum":
      if (!ENUMS[field.enum].includes(value)) errors.push(\`\${at}: \${JSON.stringify(value)} not in enum \${field.enum}\`);
      break;
    case "array":
      if (!Array.isArray(value)) errors.push(\`\${at}: expected array\`);
      else value.forEach((item, index) => checkField(field.items, item, \`\${at}[\${index}]\`, errors));
      break;
    case "map":
      if (!value || typeof value !== "object" || Array.isArray(value)) errors.push(\`\${at}: expected object map\`);
      else for (const [key, item] of Object.entries(value)) checkField(field.values, item, \`\${at}.\${key}\`, errors);
      break;
    case "ref":
      checkDefinition(TYPES[field.ref], value, at, errors);
      break;
    default:
      errors.push(\`\${at}: unknown field type \${field.type}\`);
  }
}

function checkObject(fields, value, at, errors) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    errors.push(\`\${at}: expected object\`);
    return;
  }
  for (const [name, field] of Object.entries(fields)) {
    if (!(name in value)) {
      if (field.required) errors.push(\`\${at}.\${name}: required field absent\`);
      continue;
    }
    checkField(field, value[name], \`\${at}.\${name}\`, errors);
  }
  for (const name of Object.keys(value)) {
    if (!(name in fields)) errors.push(\`\${at}.\${name}: unexpected field\`);
  }
}

function checkDefinition(definition, value, at, errors) {
  if (definition.kind === "object") {
    checkObject(definition.fields, value, at, errors);
  } else if (definition.kind === "discriminated_union") {
    for (const variant of Object.values(definition.variants)) {
      const attempt = [];
      checkObject(variant.fields, value, at, attempt);
      if (attempt.length === 0) return;
    }
    errors.push(\`\${at}: no union variant matched\`);
  } else {
    errors.push(\`\${at}: unknown definition kind\`);
  }
}

/**
 * Validate a ${contract.contract} object at its producer boundary.
 * Unknown contract_version values are REFUSED, never reinterpreted.
 */
export function validate(candidate) {
  if (!candidate || typeof candidate !== "object") {
    return ["the candidate must be one object"];
  }
  if (!SUPPORTED_VERSIONS.includes(candidate.contract_version)) {
    return [
      \`unsupported contract_version \${JSON.stringify(candidate.contract_version)}; supported: \${SUPPORTED_VERSIONS.join(", ")} — an old object must migrate explicitly, never silently reinterpret\`,
    ];
  }
  const errors = [];
  checkObject(ROOT.fields, candidate, "$", errors);
  return errors;
}
`;
}

function generatePy(contract) {
  return `# GENERATED by compile_canonical_contracts.mjs -- do not edit.
# Contract: ${contract.contract} v${contract.version}
# Pure-stdlib validation mirroring the generated JSON Schema semantics used
# by this contract (objects, maps, arrays, enums, consts, unions, patterns).
import json
import re

CONTRACT_NAME = ${JSON.stringify(contract.contract)}
CONTRACT_VERSION = ${JSON.stringify(contract.version)}
SUPPORTED_VERSIONS = ${JSON.stringify(contract.supported_versions)}
ENUMS = ${JSON.stringify(contract.enums)}
TYPES = json.loads(r'''${JSON.stringify(contract.types)}''')
ROOT = json.loads(r'''${JSON.stringify(contract.root)}''')


def _check_field(field, value, path, errors):
    kind = field["type"]
    if kind == "string":
        if not isinstance(value, str):
            errors.append(f"{path}: expected string")
        elif field.get("pattern") and not re.search(field["pattern"], value):
            errors.append(f"{path}: pattern mismatch")
    elif kind == "boolean":
        if not isinstance(value, bool):
            errors.append(f"{path}: expected boolean")
    elif kind == "number":
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            errors.append(f"{path}: expected number")
    elif kind == "null":
        if value is not None:
            errors.append(f"{path}: expected null")
    elif kind == "const":
        if value != field["const"]:
            errors.append(f"{path}: expected const {field['const']!r}")
    elif kind == "enum":
        if value not in ENUMS[field["enum"]]:
            errors.append(f"{path}: {value!r} not in enum {field['enum']}")
    elif kind == "array":
        if not isinstance(value, list):
            errors.append(f"{path}: expected array")
        else:
            for index, item in enumerate(value):
                _check_field(field["items"], item, f"{path}[{index}]", errors)
    elif kind == "map":
        if not isinstance(value, dict):
            errors.append(f"{path}: expected object map")
        else:
            for key, item in value.items():
                _check_field(field["values"], item, f"{path}.{key}", errors)
    elif kind == "ref":
        _check_definition(TYPES[field["ref"]], value, path, errors)
    else:
        errors.append(f"{path}: unknown field type {kind}")


def _check_object(fields, value, path, errors):
    if not isinstance(value, dict):
        errors.append(f"{path}: expected object")
        return
    for name, field in fields.items():
        if name not in value:
            if field.get("required"):
                errors.append(f"{path}.{name}: required field absent")
            continue
        _check_field(field, value[name], f"{path}.{name}", errors)
    for name in value:
        if name not in fields:
            errors.append(f"{path}.{name}: unexpected field")


def _check_definition(definition, value, path, errors):
    if definition["kind"] == "object":
        _check_object(definition["fields"], value, path, errors)
    elif definition["kind"] == "discriminated_union":
        attempts = []
        for variant in definition["variants"].values():
            variant_errors = []
            _check_object(variant["fields"], value, path, variant_errors)
            attempts.append(variant_errors)
            if not variant_errors:
                return
        errors.append(f"{path}: no union variant matched ({'; '.join(attempts[0])})")
    else:
        errors.append(f"{path}: unknown definition kind")


def validate(candidate):
    """Validate at the producer boundary. Unknown versions are refused."""
    if not isinstance(candidate, dict):
        return ["the candidate must be one object"]
    if candidate.get("contract_version") not in SUPPORTED_VERSIONS:
        return [
            "unsupported contract_version %r; supported: %s -- an old object must migrate explicitly, never silently reinterpret"
            % (candidate.get("contract_version"), ", ".join(SUPPORTED_VERSIONS))
        ]
    errors = []
    _check_object(ROOT["fields"], candidate, "$", errors)
    return errors
`;
}

const definitions = (await fs.readdir(CONTRACTS_DIR)).filter((name) => name.endsWith(".contract.json")).sort();
if (definitions.length === 0) throw new Error("no contract definitions found");
const receipt = { schema_version: "excel-inflow-contract-generator-receipt/1.0", generator: "compile_canonical_contracts.mjs", contracts: {} };
let dirty = [];
for (const name of definitions) {
  const bytes = await fs.readFile(path.join(CONTRACTS_DIR, name));
  const contract = JSON.parse(bytes.toString("utf8"));
  if (contract.schema_version !== "excel-inflow-contract-definition/1.0") {
    throw new Error(`${name}: unsupported definition schema`);
  }
  const base = name.replace(".contract.json", "");
  const outputs = {
    [path.join(GENERATED_SCHEMA_DIR, `${base}.generated.schema.json`)]:
      `${JSON.stringify(generateSchema(contract), null, 2)}\n`,
    [path.join(GENERATED_JS_DIR, `${base.replace(/-/g, "_")}_contract.mjs`)]:
      generateJs(contract),
    [path.join(GENERATED_PY_DIR, `${base.replace(/-/g, "_")}_contract.py`)]:
      generatePy(contract),
  };
  receipt.contracts[contract.contract] = {
    definition: `assets/contracts/${name}`,
    definition_sha256: createHash("sha256").update(bytes).digest("hex"),
    version: contract.version,
    outputs: {},
  };
  for (const [target, body] of Object.entries(outputs)) {
    receipt.contracts[contract.contract].outputs[path.relative(ROOT, target)] =
      createHash("sha256").update(body).digest("hex");
    const existing = await fs.readFile(target, "utf8").catch(() => null);
    if (existing !== body) {
      if (CHECK) dirty.push(path.relative(ROOT, target));
      else {
        await fs.mkdir(path.dirname(target), { recursive: true });
        await fs.writeFile(target, body, "utf8");
      }
    }
  }
}
const receiptPath = path.join(GENERATED_SCHEMA_DIR, "contract-generator-receipt.json");
const receiptBody = `${JSON.stringify(receipt, null, 2)}\n`;
const existingReceipt = await fs.readFile(receiptPath, "utf8").catch(() => null);
if (existingReceipt !== receiptBody) {
  if (CHECK) dirty.push(path.relative(ROOT, receiptPath));
  else {
    await fs.mkdir(path.dirname(receiptPath), { recursive: true });
    await fs.writeFile(receiptPath, receiptBody, "utf8");
  }
}
if (CHECK && dirty.length > 0) {
  console.error(`GENERATED_DIFF_DIRTY: ${dirty.join(", ")} — run compile_canonical_contracts.mjs and commit the result`);
  process.exit(1);
}
console.log(JSON.stringify({ status: "PASS", mode: CHECK ? "check" : "write", contracts: definitions.length }));
