#!/usr/bin/env node
/**
 * run_doc_single_source_tests.mjs — drift-gate tests for the single-sourced
 * instruction docs (SKILL.md -> central-instructions.md, references/runtime-core.md).
 *
 * Asserts:
 *   1. Generator determinism: two consecutive runs emit identical bytes and
 *      are idempotent against disk.
 *   2. `--check` catches induced drift in each generated file (exit 1) and
 *      passes again once restored (exit 0).
 *   3. Generated files contain no YAML frontmatter.
 *   4. Shared-body hash equality: after removing SKILL.md's frontmatter and
 *      reversing the declared runtime-core H1 override, all three files hash
 *      identically — proving a single shared body.
 *
 * Usage: node scripts/run_doc_single_source_tests.mjs   (exit 0 = all pass)
 */

import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { applyTransforms, generateAll, stripFrontmatter } from './generate_instruction_docs.mjs';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const GENERATOR = 'scripts/generate_instruction_docs.mjs';
const CANONICAL = 'SKILL.md';
const GENERATED = ['central-instructions.md', join('references', 'runtime-core.md')];

let failures = 0;
function check(name, ok, detail = '') {
  console.log(`${ok ? 'PASS' : 'FAIL'}: ${name}${ok || !detail ? '' : ` — ${detail}`}`);
  if (!ok) failures += 1;
}

function runGenerator(args) {
  return spawnSync(process.execPath, [join(GENERATOR), ...args], { cwd: REPO_ROOT, encoding: 'utf8' });
}

function sha256(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

function readRepo(path) {
  return readFileSync(join(REPO_ROOT, path), 'utf8');
}

// --- T0/T1: regenerate to a consistent baseline, then prove determinism ------
const gen1 = runGenerator([]);
check('T0 generator runs cleanly', gen1.status === 0, gen1.stderr);
const hashesRun1 = Object.fromEntries(GENERATED.map((p) => [p, sha256(readRepo(p))]));
const gen2 = runGenerator([]);
check('T1a second generator run exits 0', gen2.status === 0, gen2.stderr);
const hashesRun2 = Object.fromEntries(GENERATED.map((p) => [p, sha256(readRepo(p))]));
check(
  'T1b generator is byte-deterministic across runs',
  JSON.stringify(hashesRun1) === JSON.stringify(hashesRun2),
  `run1=${JSON.stringify(hashesRun1)} run2=${JSON.stringify(hashesRun2)}`
);

try {
  // --- T2: --check catches induced drift in each generated file --------------
  for (const path of GENERATED) {
    const original = readRepo(path);
    try {
      const drifted = `${original}<!-- induced drift for doc-single-source drift gate -->\n`;
      const { writeFileSync } = await import('node:fs');
      writeFileSync(join(REPO_ROOT, path), drifted, 'utf8');
      const res = runGenerator(['--check']);
      check(
        `T2 --check detects induced drift in ${path}`,
        res.status === 1 && res.stderr.includes(path),
        `exit=${res.status} stderr=${res.stderr.trim()}`
      );
    } finally {
      const { writeFileSync } = await import('node:fs');
      writeFileSync(join(REPO_ROOT, path), original, 'utf8'); // restore even on failure
    }
  }
  const clean = runGenerator(['--check']);
  check('T2b --check exits 0 after restore', clean.status === 0, clean.stderr);

  // --- T3: no frontmatter leaks into generated files -------------------------
  for (const path of GENERATED) {
    const text = readRepo(path);
    check(
      `T3 ${path} has no YAML frontmatter`,
      !text.startsWith('---\n') && !text.includes('name: excel-inflow')
    );
  }

  // --- T4: shared-body hash equality ------------------------------------------
  const canonicalBody = stripFrontmatter(readRepo(CANONICAL));
  const centralHash = sha256(readRepo('central-instructions.md'));
  const coreText = readRepo(join('references', 'runtime-core.md'));
  const coreReversed = applyTransforms(coreText, [
    { kind: 'set-first-h1', value: '# Excel Inflow' },
  ]);
  const coreHash = sha256(coreReversed);
  const canonicalHash = sha256(canonicalBody);
  check(
    'T4 shared-body hash equal across all three docs',
    canonicalHash === centralHash && centralHash === coreHash,
    `skill=${canonicalHash.slice(0, 12)} central=${centralHash.slice(0, 12)} core=${coreHash.slice(0, 12)}`
  );

  // --- T5: generated bytes equal an independent regeneration of canonical -----
  const expected = generateAll(readRepo(CANONICAL));
  let t5ok = true;
  let t5detail = '';
  for (const { path, content } of expected) {
    if (readRepo(path) !== content) {
      t5ok = false;
      t5detail += ` ${path} stale;`;
    }
  }
  check('T5 on-disk generated files match fresh generation of SKILL.md', t5ok, t5detail);
} finally {
  // Leave the tree consistent regardless of test outcome.
  runGenerator([]);
}

if (failures > 0) {
  console.error(`\n${failures} test(s) FAILED.`);
  process.exit(1);
}
console.log('\nAll doc-single-source tests passed.');
