#!/usr/bin/env node
/**
 * run_doc_single_source_tests.mjs — drift-gate tests for the single-sourced
 * instruction docs (SKILL.md -> central-instructions.md, references/runtime-core.md).
 *
 * Asserts:
 *   1. Generator determinism: two consecutive runs emit identical bytes and
 *      are idempotent against disk.
 *   2. `--check` catches induced drift in each generated file (exit 1) and
 *      passes again once restored (exit 0).
 *   3. Generated files contain no YAML frontmatter.
 *   4. Shared-body hash equality: after removing SKILL.md's frontmatter and
 *      reversing the declared runtime-core H1 override, all three files hash
 *      identically — proving a single shared body.
 *
 * Usage: node scripts/run_doc_single_source_tests.mjs   (exit 0 = all pass)
 */

import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import process from 'node:process';

import {
  applyTransforms,
  generateAll,
  removeInstructionMirrorBanner,
  stripFrontmatter,
} from './generate_instruction_docs.mjs';
import { createRunner } from './lib/test_harness.mjs';

const run = createRunner({ name: 'doc_single_source_tests', importMetaUrl: import.meta.url });
const REPO_ROOT = run.ROOT;
const GENERATOR = 'scripts/generate_instruction_docs.mjs';
const CANONICAL = 'SKILL.md';
const GENERATED = ['central-instructions.md', join('references', 'runtime-core.md')];

function runGenerator(args, root = REPO_ROOT) {
  return spawnSync(process.execPath, [join(REPO_ROOT, GENERATOR), ...args, '--root', root], { cwd: REPO_ROOT, encoding: 'utf8' });
}

function sha256(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

function readRepo(path) {
  return readFileSync(join(REPO_ROOT, path), 'utf8');
}

const scratch = mkdtempSync(join(tmpdir(), 'excel-inflow-doc-single-source-'));
try {
  cpSync(join(REPO_ROOT, CANONICAL), join(scratch, CANONICAL));
  for (const relative of GENERATED) {
    const target = join(scratch, relative);
    mkdirSync(join(target, '..'), { recursive: true });
    cpSync(join(REPO_ROOT, relative), target, { recursive: true });
  }

  // --- T0/T1: read-only check, scratch regeneration, determinism ------------
  const cleanCheck = runGenerator(['--check']);
  run.ok(cleanCheck.status === 0, 'T0 committed instruction mirrors pass the read-only exact-regeneration check');
  const gen1 = runGenerator([], scratch);
  run.ok(gen1.status === 0, 'T1a sanctioned writer runs cleanly in scratch');
  const hashesRun1 = Object.fromEntries(GENERATED.map((p) => [p, sha256(readFileSync(join(scratch, p), 'utf8'))]));
  const gen2 = runGenerator([], scratch);
  run.ok(gen2.status === 0, 'T1b second scratch writer run exits 0');
  const hashesRun2 = Object.fromEntries(GENERATED.map((p) => [p, sha256(readFileSync(join(scratch, p), 'utf8'))]));
  run.ok(JSON.stringify(hashesRun1) === JSON.stringify(hashesRun2), 'T1c generator is byte-deterministic across runs');

  // --- T2: --check catches induced drift in each generated file --------------
  for (const path of GENERATED) {
    const target = join(scratch, path);
    const original = readFileSync(target, 'utf8');
    writeFileSync(target, `${original}<!-- induced drift for doc-single-source drift gate -->\n`, 'utf8');
    const res = runGenerator(['--check'], scratch);
    run.ok(res.status === 1 && res.stderr.includes(path), `T2 --check detects induced drift in ${path}`);
    writeFileSync(target, original, 'utf8');
  }
  const clean = runGenerator(['--check'], scratch);
  run.ok(clean.status === 0, 'T2b --check exits 0 after restore');

  // --- T3: no frontmatter leaks into generated files -------------------------
  for (const path of GENERATED) {
    const text = readRepo(path);
    run.ok(!text.startsWith('---\n') && !text.includes('name: excel-inflow'), `T3 ${path} has no YAML frontmatter`);
    run.ok(text.includes('generated-document:instruction-mirror/1.0') && text.includes('Do not hand-edit'), `T3b ${path} carries an unambiguous generator and drift-remedy banner`);
  }

  // --- T4: shared-body hash equality ------------------------------------------
  const canonicalBody = stripFrontmatter(readRepo(CANONICAL));
  const centralHash = sha256(removeInstructionMirrorBanner(readRepo('central-instructions.md')));
  const coreText = removeInstructionMirrorBanner(readRepo(join('references', 'runtime-core.md')));
  const coreReversed = applyTransforms(coreText, [
    { kind: 'set-first-h1', value: '# Excel Inflow' },
  ]);
  const coreHash = sha256(coreReversed);
  const canonicalHash = sha256(canonicalBody);
  run.ok(canonicalHash === centralHash && centralHash === coreHash, 'T4 shared-body hash equal across all three docs');

  // --- T5: generated bytes equal an independent regeneration of canonical -----
  const expected = generateAll(readRepo(CANONICAL));
  let t5ok = true;
  let t5detail = '';
  for (const { path, content } of expected) {
    if (readRepo(path) !== content) {
      t5ok = false;
      t5detail += ` ${path} stale;`;
    }
  }
  run.ok(t5ok, 'T5 on-disk generated files match fresh generation of SKILL.md');
} finally {
  rmSync(scratch, { recursive: true, force: true });
}

run.finish();
