#!/usr/bin/env node
/**
 * run_doc_single_source_tests.mjs — drift-gate tests for the single-sourced
 * instruction docs (SKILL.md -> central-instructions.md, references/runtime-core.md).
 *
 * Asserts:
 *   1. Generator determinism: two consecutive runs emit identical bytes and
 *      are idempotent against disk.
 *   2. `--check` catches induced drift in each generated file (exit 1) and
 *      passes again once restored (exit 0).
 *   3. Generated files contain no YAML frontmatter.
 *   4. Shared-body hash equality: after removing SKILL.md's frontmatter and
 *      reversing the declared runtime-core H1 override, all three files hash
 *      identically — proving a single shared body.
 *
 * Usage: node scripts/run_doc_single_source_tests.mjs   (exit 0 = all pass)
 */

import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import process from 'node:process';

import { applyTransforms, generateAll, stripFrontmatter } from './generate_instruction_docs.mjs';
import { createRunner } from './lib/test_harness.mjs';

const run = createRunner({ name: 'doc_single_source_tests', importMetaUrl: import.meta.url });
const REPO_ROOT = run.ROOT;
const GENERATOR = 'scripts/generate_instruction_docs.mjs';
const CANONICAL = 'SKILL.md';
const GENERATED = ['central-instructions.md', join('references', 'runtime-core.md')];

function runGenerator(args) {
  return spawnSync(process.execPath, [join(GENERATOR), ...args], { cwd: REPO_ROOT, encoding: 'utf8' });
}

function sha256(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

function readRepo(path) {
  return readFileSync(join(REPO_ROOT, path), 'utf8');
}

// --- T0/T1: regenerate to a consistent baseline, then prove determinism ------
const gen1 = runGenerator([]);
run.ok(gen1.status === 0, 'T0 generator runs cleanly');
const hashesRun1 = Object.fromEntries(GENERATED.map((p) => [p, sha256(readRepo(p))]));
const gen2 = runGenerator([]);
run.ok(gen2.status === 0, 'T1a second generator run exits 0');
const hashesRun2 = Object.fromEntries(GENERATED.map((p) => [p, sha256(readRepo(p))]));
run.ok(JSON.stringify(hashesRun1) === JSON.stringify(hashesRun2), 'T1b generator is byte-deterministic across runs');

try {
  // --- T2: --check catches induced drift in each generated file --------------
  for (const path of GENERATED) {
    const original = readRepo(path);
    try {
      const drifted = `${original}<!-- induced drift for doc-single-source drift gate -->\n`;
      const { writeFileSync } = await import('node:fs');
      writeFileSync(join(REPO_ROOT, path), drifted, 'utf8');
      const res = runGenerator(['--check']);
      run.ok(res.status === 1 && res.stderr.includes(path), `T2 --check detects induced drift in ${path}`);
    } finally {
      const { writeFileSync } = await import('node:fs');
      writeFileSync(join(REPO_ROOT, path), original, 'utf8'); // restore even on failure
    }
  }
  const clean = runGenerator(['--check']);
  run.ok(clean.status === 0, 'T2b --check exits 0 after restore');

  // --- T3: no frontmatter leaks into generated files -------------------------
  for (const path of GENERATED) {
    const text = readRepo(path);
    run.ok(!text.startsWith('---\n') && !text.includes('name: excel-inflow'), `T3 ${path} has no YAML frontmatter`);
  }

  // --- T4: shared-body hash equality ------------------------------------------
  const canonicalBody = stripFrontmatter(readRepo(CANONICAL));
  const centralHash = sha256(readRepo('central-instructions.md'));
  const coreText = readRepo(join('references', 'runtime-core.md'));
  const coreReversed = applyTransforms(coreText, [
    { kind: 'set-first-h1', value: '# Excel Inflow' },
  ]);
  const coreHash = sha256(coreReversed);
  const canonicalHash = sha256(canonicalBody);
  run.ok(canonicalHash === centralHash && centralHash === coreHash, 'T4 shared-body hash equal across all three docs');

  // --- T5: generated bytes equal an independent regeneration of canonical -----
  const expected = generateAll(readRepo(CANONICAL));
  let t5ok = true;
  let t5detail = '';
  for (const { path, content } of expected) {
    if (readRepo(path) !== content) {
      t5ok = false;
      t5detail += ` ${path} stale;`;
    }
  }
  run.ok(t5ok, 'T5 on-disk generated files match fresh generation of SKILL.md');
} finally {
  // Leave the tree consistent regardless of test outcome.
  runGenerator([]);
}

run.finish();
